logLevel = "debug"

preload = ["./treaty-utilities/mock-create-histogram.ts",  "./treaty-utilities/routes.ts", "./treaty-utilities/angular-ivy.ts"]

[test]
preload = ["./treaty-utilities/setup-tests.ts"]
