[workspace]
members = [
  "ngx",
  "ngx/transform"
]


resolver = "2"


[profile.release]
codegen-units = 1
# debug = true
lto = true

# Optimize for size
opt-level = "s"

# Strip debug symbols
strip = "symbols"